#version: '3.8'

services:
  angular-app:
    build:
      context: ./angular
      dockerfile: Dockerfile.angular
    ports:
      - "4200:4200"
    depends_on:
      - python-app
      - geoserver

  python-app:
    container_name: python_app
    build:
      context: ./geoserver_python
      dockerfile: Dockerfile.python
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
#      - celery-app-tasks
      - celery-beat
      - redis
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Maxval@123
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - CELERY_BEAT_SCHEDULER=django_celery_beat.schedulers:DatabaseScheduler
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 32G
    command: ./manage.py runserver 0.0.0.0:5000

  geoserver:
    container_name: geoserver
    build:
      context: ./geoserver
      dockerfile: Dockerfile.geoserver
    ports:
      - "8081:8080"
    volumes:
      - geoserver_data:/var/lib/geoserver/data
    depends_on:
      - db

  db:
    container_name: db
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Maxval@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 32G

  celery-app-tasks:
    container_name: celery-app-tasks
    build:
      context: ./geoserver_python
      dockerfile: Dockerfile.python
    volumes:
      - .:/app
    working_dir: /app/geoserver_python/
    command: celery -A geoserver_python worker --loglevel=info --uid=nobody --gid=nogroup
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 32G
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379

  celery-beat:
    container_name: celery-beat
    build:
      context: ./geoserver_python
      dockerfile: Dockerfile.python
    command: celery -A geoserver_python beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 32G
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - CELERY_BEAT_SCHEDULER=django_celery_beat.schedulers:DatabaseScheduler

volumes:
  postgres_data:
  geoserver_data:
