FROM python:3.11

WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Install GDAL for PostGIS support
RUN apt-get update && \
    apt-get install -y binutils libproj-dev gdal-bin

# Copy the rest of the application code
COPY . .

# Collect static files
RUN python manage.py collectstatic --noinput

# Apply database migrations
RUN python manage.py migrate

EXPOSE 5000

CMD ["python", "manage.py", "runserver", "0.0.0.0:5000"]