# Generated by Django 3.2.25 on 2024-06-10 08:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GISContour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'verbose_name': 'GIS Model',
                'verbose_name_plural': 'GIS Models',
            },
        ),
        migrations.CreateModel(
            name='GISPointModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('grading', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'GIS Model',
                'verbose_name_plural': 'GIS Models',
            },
        ),
    ]
