# Generated by Django 4.2.13 on 2024-07-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoserver_python', '0002_gisdelunarytrianglemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gispointmodel',
            name='bottom_of_pile',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
